<a href="https://colab.research.google.com/github/ucfilho/ANN_raianars/blob/master/ANN_001_gera_matriz_classifica_OUT_18_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# este comando clona o diretorio github ucfilho/ANN no colaboratory research
!git clone https://github.com/RaianaSeixas/ANN #clonar do Github
%cd ANN
#!ls
print("Hello world"+"\n"+"I'm evolving!!!"+"\n")

%matplotlib inline

Cloning into 'ANN'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 76 (delta 1), reused 0 (delta 0), pack-reused 70
Unpacking objects: 100% (76/76), done.
/content/ANN/ANN/ANN
Hello world
I'm evolving!!!



In [0]:
!ls

000_ANN_Gera_Matriz_out_04_2019.ipynb		    X_DAT_B_set_17_2019.csv
000_ANN_parte_001_XY_dados_out_01_2019.ipynb	    X_DAT_set_17_2019.csv
000_ANN_parte_002_XY_Métricas_D10_OUT_4_2019.ipynb  XY_D10_30_out_7_2019.csv
000_ANN_parte_009_Métricas_PCA_OUT_07_2019.ipynb    XY_D10_out_1_2019.csv
000_Gerenciador_DE_var_F_CR_STAT_set_27_2019.ipynb  XY_D10_out_5_2019.csv
imput_ANN_D10_30_out_07_19.zip			    XY_schwefel_out_11_19.csv
imput_ANN_D10_6F.zip				    Y_DAT_B_set_17_2019.csv
imput_ANN_D10_out_05_19.zip			    Y_DAT_set_17_2019.csv
imput_ANN_schwefel_out_11_19.zip


In [0]:
# Functions
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def tasig(x,deriv=False):
    if(deriv==True):
        return 1-x*x
    return 2/(1+np.exp(-2*x))-1

# purelin function
def purelin(x,deriv=False):
    if(deriv==True):
        return 1
    #N=len(x)
    #for i in range(N):
      #if (x[i]>1):
        #x[i]=1
    return x

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [0]:
def ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,X_train,y):
  syn0 = 2*np.random.random((Neuron_input,Neuron_hidden)) - 1
  syn1 = 2*np.random.random((Neuron_hidden,Neuron_output)) - 1
  for j in range(Epoch):
    l0 = X_train
    l1 = tasig(np.dot(l0,syn0))
    l2 = purelin(np.dot(l1,syn1))
    l2_error = y - l2
    l2_delta = l2_error*purelin(l2,deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * tasig(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)*Learning_rate
    syn0 += l0.T.dot(l1_delta)*Learning_rate
  return syn0,syn1



In [0]:
def ANN_ycal(syn0,syn1,X_train):
  l0 = X_train
  l1 = tasig(np.dot(l0,syn0))
  l2 = purelin(np.dot(l1,syn1))
  y_calc=np.reshape(l2,len(l2))
  return y_calc

In [0]:
def Classifica(ycalc):
  n=len(ycalc)
  for i in range(n):
    if(ycalc[i]<0):
      ycalc[i]=-1
    else:
      ycalc[i]=1
  return ycalc

In [0]:
def PrecisaoGlobal(tn, fp, fn, tp):
  PrecGlob=(tn+tp)/(tn+ fp+ fn+ tp)
  return PrecGlob

In [0]:
# leitura dos dados
DAT=pd.read_csv("XY_D10_30_out_7_2019.csv")
#print(DAT.head())

In [0]:
# separa as colunas de interesse
Index=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
Dat_Select=[]
Dat_Select=DAT.iloc[:,Index].copy()

pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 30)
#print(Dat_Select)
#print(Dat_Select.head())

In [0]:
DAT_OLD=[]
DAT_OLD=Dat_Select.copy()
DAT=Normatiza(Dat_Select)

In [0]:
ColF=DAT_OLD['F']
W=np.array(DAT_OLD['F'])
Wo=np.array(DAT_OLD['Fo'])
for i in range(len(W)):
  W[i]=W[i]-Wo[i]
  if(W[i]<0):
    W[i]=-1
  else:
    W[i]=1
DAT['F'] = W

In [0]:
# obtem as variaveis independentes (treino e teste)
# separa os dados em treino e teste
train=DAT.sample(frac=0.8,random_state=None) 
test=DAT.drop(train.index)
IND=[1,2,3,4,6,7,8,9,10,11,12,13,14]
x_train=train.iloc[:,IND]
x_test=test.iloc[:,IND]
X_OLD=DAT_OLD.iloc[:,IND]
X_NOME=DAT_OLD.columns[IND]
print(X_NOME)


Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')


In [0]:
MELHOR_PRECISAO=0
MAT0=[]
MAT1=[]
CONFUSAO=[]

In [0]:
# obtem as variaveis dependentes (treino e teste)
Index=[15] #F
#Index=[16] #CR
y_train=train.iloc[:,Index]
y_test=test.iloc[:,Index]
Y_OLD=DAT_OLD.iloc[:,Index]
#print(y_train.head())

In [0]:
y_train=np.array(y_train)
Nomes=x_train.columns
x_test=np.array(x_test)
x_train=np.array(x_train)

In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.001
omega=0.9
Epoch=20000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_calc_test=ANN_ycal(syn0,syn1,x_test)

In [0]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))


Epocas= 20000 Learning rate= 0.001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')
Treino precisao global= 0.9900990099009901
Treino tn: 51  fp: 0 fn: 1 tp: 49
[[51  0]
 [ 1 49]]
Teste: precisao global= 0.6
Teste tn: 9  fp: 5 fn: 5 tp: 6
[[9 5]
 [5 6]]


**So para lembrar q o .ravel() existe!!**

In [0]:
print(confusion_matrix(y_calc_test,y_obs_test))
print(confusion_matrix(y_calc_test,y_obs_test).ravel())
a,b,c,d,e,f,g,h=[1,2,3,4,5,6,7,99]
print(h)

[[9 5]
 [5 6]]
[9 5 5 6]
99


In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.0001
omega=0.9
Epoch=100000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_obs_test=y_test
y_calc_test=ANN_ycal(syn0,syn1,x_test)



In [0]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))

Epocas= 100000 Learning rate= 0.0001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')
Treino precisao global= 1.0
Treino tn: 52  fp: 0 fn: 0 tp: 49
[[52  0]
 [ 0 49]]
Teste: precisao global= 0.64
Teste tn: 10  fp: 5 fn: 4 tp: 6
[[10  5]
 [ 4  6]]


In [0]:
# print(X_NOME)

In [0]:
# ========= Novas mudancas ==================================================
IND=[1,2,6,7]
x_train=train.iloc[:,IND]
x_test=test.iloc[:,IND]
X_OLD=DAT_OLD.iloc[:,IND]
X_NOME=DAT_OLD.columns[IND]
print(X_NOME)
y_train=np.array(y_train)
x_test=np.array(x_test)
x_train=np.array(x_train)

Index(['DI RELATIVO', 'FRAC Its', 'Fo', 'CRo'], dtype='object')


In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.0001
omega=0.9
Epoch=300000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_obs_test=y_test
y_calc_test=ANN_ycal(syn0,syn1,x_test)



In [0]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))



Epocas= 300000 Learning rate= 0.0001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'Fo', 'CRo'], dtype='object')
Treino precisao global= 0.8712871287128713
Treino tn: 47  fp: 8 fn: 5 tp: 41
[[47  8]
 [ 5 41]]
Teste: precisao global= 0.72
Teste tn: 10  fp: 3 fn: 4 tp: 8
[[10  3]
 [ 4  8]]


In [0]:
print("Melhor precisao=",MELHOR_PRECISAO)
print(MAT0)
print(MAT1)
nl0=MAT0.shape[0];nc0=MAT0.shape[1]
nl1=MAT1.shape[0];nc1=MAT1.shape[1]
print("colunas %d e linhas %d MAT0" % (nc0,nl0))
print("colunas %d e linhas %d MAT1" % (nc1,nl1))
print(CONF_teste)
print(CONF_treino)

Melhor precisao= 0.72
[[-2.2451523   1.44647017 -1.42525924 -1.04950789  0.90698793  0.17869166
   1.67866068  0.48119467 -1.67045608]
 [-1.73434273 -0.01352672 -3.33598937 -0.58648365  0.3633048   0.84434149
   4.26364034  0.02383794 -2.75085005]
 [-3.67269544  4.45029704  0.01140948 -4.18075988  1.4732019  -4.49958934
   0.60969933 -0.57032133  0.17368931]
 [-1.92583246 -0.93725304  1.29062356 -1.96620227 -0.00890646  1.79303483
  -2.75163919  0.95214866 -0.2276709 ]]
[[-2.85685105]
 [ 2.51821611]
 [ 3.54052363]
 [ 2.8105423 ]
 [-2.77062347]
 [ 1.00639321]
 [ 2.24710669]
 [ 0.01173604]
 [-1.47390986]]
colunas 9 e linhas 4 MAT0
colunas 1 e linhas 9 MAT1
[[10  3]
 [ 4  8]]
[[47  8]
 [ 5 41]]


In [0]:
Nomes=['OTIMO','PARTIC_best','Xresp']
print("Melhor precisao=",MELHOR_PRECISAO)
print(MAT0)
print(MAT1)
nl0=MAT0.shape[0];nc0=MAT0.shape[1]
nl1=MAT1.shape[0];nc1=MAT1.shape[1]
print("colunas %d e linhas %d MAT0" % (nc0,nl0))
print("colunas %d e linhas %d MAT1" % (nc1,nl1))
print(CONF_teste)
print(CONF_treino)
BUSCA=pd.Series([OTIMO,PARTIC_best,Xresp],index=Nomes )

Melhor precisao= 0.72
[[-2.2451523   1.44647017 -1.42525924 -1.04950789  0.90698793  0.17869166
   1.67866068  0.48119467 -1.67045608]
 [-1.73434273 -0.01352672 -3.33598937 -0.58648365  0.3633048   0.84434149
   4.26364034  0.02383794 -2.75085005]
 [-3.67269544  4.45029704  0.01140948 -4.18075988  1.4732019  -4.49958934
   0.60969933 -0.57032133  0.17368931]
 [-1.92583246 -0.93725304  1.29062356 -1.96620227 -0.00890646  1.79303483
  -2.75163919  0.95214866 -0.2276709 ]]
[[-2.85685105]
 [ 2.51821611]
 [ 3.54052363]
 [ 2.8105423 ]
 [-2.77062347]
 [ 1.00639321]
 [ 2.24710669]
 [ 0.01173604]
 [-1.47390986]]
colunas 9 e linhas 4 MAT0
colunas 1 e linhas 9 MAT1
[[10  3]
 [ 4  8]]
[[47  8]
 [ 5 41]]


NameError: ignored

In [0]:
TESTE=np.array([[1,2,3],[4,5,6]])
print(TESTE)
print(TESTE.shape)