<a href="https://colab.research.google.com/github/ucfilho/ANN_raianars/blob/master/ANN_parte_002_gera_matriz_classifica_OUT_18_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# este comando clona o diretorio github ucfilho/ANN no colaboratory research
!git clone https://github.com/RaianaSeixas/ANN #clonar do Github
%cd ANN
#!ls
print("Hello world"+"\n"+"I'm evolving!!!"+"\n")

%matplotlib inline

fatal: destination path 'ANN' already exists and is not an empty directory.
/content/ANN
Hello world
I'm evolving!!!



In [2]:
!ls

000_ANN_Gera_Matriz_out_04_2019.ipynb
000_ANN_parte_001_XY_dados_out_01_2019.ipynb
000_ANN_parte_002_XY_Métricas_D10_OUT_4_2019.ipynb
000_ANN_parte_009_Métricas_PCA_OUT_07_2019.ipynb
000_Gerenciador_DE_var_F_CR_STAT_set_27_2019.ipynb
ANN
ANN__2019-10-18_19h34min.csv
ANN_2019-10-18_19h34min.csv
ANN2019-10-18_19h34min.csv
ANN_2019-10-18_19h35min.csv
ANN_read_matrix
drive
imput_ANN_D10_30_out_07_19.zip
imput_ANN_D10_6F.zip
imput_ANN_D10_out_05_19.zip
imput_ANN_schwefel_out_11_19.zip
X_DAT_B_set_17_2019.csv
X_DAT_set_17_2019.csv
XY_D10_30_out_7_2019.csv
XY_D10_out_1_2019.csv
XY_D10_out_5_2019.csv
XY_schwefel_out_11_19.csv
Y_DAT_B_set_17_2019.csv
Y_DAT_set_17_2019.csv


In [0]:
# Functions
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def tasig(x,deriv=False):
    if(deriv==True):
        return 1-x*x
    return 2/(1+np.exp(-2*x))-1

# purelin function
def purelin(x,deriv=False):
    if(deriv==True):
        return 1
    #N=len(x)
    #for i in range(N):
      #if (x[i]>1):
        #x[i]=1
    return x

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [0]:
def ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,X_train,y):
  syn0 = 2*np.random.random((Neuron_input,Neuron_hidden)) - 1
  syn1 = 2*np.random.random((Neuron_hidden,Neuron_output)) - 1
  for j in range(Epoch):
    l0 = X_train
    l1 = tasig(np.dot(l0,syn0))
    l2 = purelin(np.dot(l1,syn1))
    l2_error = y - l2
    l2_delta = l2_error*purelin(l2,deriv=True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * tasig(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)*Learning_rate
    syn0 += l0.T.dot(l1_delta)*Learning_rate
  return syn0,syn1



In [0]:
def ANN_ycal(syn0,syn1,X_train):
  l0 = X_train
  l1 = tasig(np.dot(l0,syn0))
  l2 = purelin(np.dot(l1,syn1))
  y_calc=np.reshape(l2,len(l2))
  return y_calc

In [0]:
def Classifica(ycalc):
  n=len(ycalc)
  for i in range(n):
    if(ycalc[i]<0):
      ycalc[i]=-1
    else:
      ycalc[i]=1
  return ycalc

In [0]:
def PrecisaoGlobal(tn, fp, fn, tp):
  PrecGlob=(tn+tp)/(tn+ fp+ fn+ tp)
  return PrecGlob

In [0]:
# leitura dos dados
DAT=pd.read_csv("XY_D10_30_out_7_2019.csv")
#print(DAT.head())
#print(len(DAT))

In [0]:
# separa as colunas de interesse
Index=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
Dat_Select=[]
Dat_Select=DAT.iloc[:,Index].copy()

pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 30)
#print(Dat_Select)
#print(Dat_Select.head())

In [0]:
DAT_OLD=[]
DAT_OLD=Dat_Select.copy()
DAT=Normatiza(Dat_Select)

In [0]:
ColF=DAT_OLD['F']
W=np.array(DAT_OLD['F'])
Wo=np.array(DAT_OLD['Fo'])
for i in range(len(W)):
  W[i]=W[i]-Wo[i]
  if(W[i]<0):
    W[i]=-1
  else:
    W[i]=1
DAT['F'] = W

In [14]:
# obtem as variaveis independentes (treino e teste)
# separa os dados em treino e teste
train=DAT.sample(frac=0.8,random_state=None) 
test=DAT.drop(train.index)
IND=[1,2,3,4,6,7,8,9,10,11,12,13,14]
x_train=train.iloc[:,IND]
x_test=test.iloc[:,IND]
X_OLD=DAT_OLD.iloc[:,IND]
X_NOME=DAT_OLD.columns[IND]
print(X_NOME)


Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')


In [0]:
MELHOR_PRECISAO=0
MAT0=[]
MAT1=[]
CONFUSAO=[]

In [0]:
# obtem as variaveis dependentes (treino e teste)
Index=[15] #F
#Index=[16] #CR
y_train=train.iloc[:,Index]
y_test=test.iloc[:,Index]
Y_OLD=DAT_OLD.iloc[:,Index]
#print(y_train.head())

In [0]:
y_train=np.array(y_train)
Nomes=x_train.columns
x_test=np.array(x_test)
x_train=np.array(x_train)

In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.001
omega=0.9
Epoch=20000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_calc_test=ANN_ycal(syn0,syn1,x_test)

In [19]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))


Epocas= 20000 Learning rate= 0.001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')
Treino precisao global= 0.9900990099009901
Treino tn: 56  fp: 1 fn: 0 tp: 44
[[56  1]
 [ 0 44]]
Teste: precisao global= 0.6
Teste tn: 7  fp: 7 fn: 3 tp: 8
[[7 7]
 [3 8]]


**So para lembrar q o .ravel() existe!!**

In [20]:
print(confusion_matrix(y_calc_test,y_obs_test))
print(confusion_matrix(y_calc_test,y_obs_test).ravel())
a,b,c,d,e,f,g,h=[1,2,3,4,5,6,7,99]
print(h)

[[7 7]
 [3 8]]
[7 7 3 8]
99


In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.0001
omega=0.9
Epoch=100000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_obs_test=y_test
y_calc_test=ANN_ycal(syn0,syn1,x_test)



In [22]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))

Epocas= 100000 Learning rate= 0.0001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'VELOC FOBJ', 'VELOC X', 'Fo', 'CRo', 'fmin',
       'fmax', 'AD_fmin', 'AD_fmax', 'DELTA FOBJ', 'DELTA VX', 'r_fitness'],
      dtype='object')
Treino precisao global= 1.0
Treino tn: 56  fp: 0 fn: 0 tp: 45
[[56  0]
 [ 0 45]]
Teste: precisao global= 0.48
Teste tn: 5  fp: 8 fn: 5 tp: 7
[[5 8]
 [5 7]]


In [0]:
# print(X_NOME)

In [24]:
# ========= Novas mudancas ==================================================
IND=[1,2,6,7]
x_train=train.iloc[:,IND]
x_test=test.iloc[:,IND]
X_OLD=DAT_OLD.iloc[:,IND]
X_NOME=DAT_OLD.columns[IND]
print(X_NOME)
y_train=np.array(y_train)
x_test=np.array(x_test)
x_train=np.array(x_train)

Index(['DI RELATIVO', 'FRAC Its', 'Fo', 'CRo'], dtype='object')


In [0]:
# input dataset
Neuron_input=len(X_NOME)
Neuron_hidden=9
Neuron_output=1
Learning_rate=0.0001
omega=0.9
Epoch=300000
syn0,syn1=ANN(Epoch,Neuron_input,Neuron_hidden,Neuron_output,Learning_rate,x_train,y_train)
y_obs_train=y_train
y_obs_test=y_test
y_calc_train=ANN_ycal(syn0,syn1,x_train)
y_obs_test=y_test
y_calc_test=ANN_ycal(syn0,syn1,x_test)



In [26]:
print("Epocas=",Epoch,"Learning rate=",Learning_rate,"Dados teste matriz confusao:")
print(X_NOME)
print("====================================")
y_calc_train = Classifica(y_calc_train)
y_calc_test = Classifica(y_calc_test)



tn, fp, fn, tp = confusion_matrix(y_calc_train,y_obs_train).ravel()
PrecTreino=PrecisaoGlobal(tn, fp, fn, tp)
print("Treino precisao global=",PrecTreino)
print("Treino tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_train,y_obs_train))


print("====================================")
tn, fp, fn, tp = confusion_matrix(y_calc_test,y_obs_test).ravel()
PrecTeste=PrecisaoGlobal(tn, fp, fn, tp)
print("Teste: precisao global=",PrecTeste)
print("Teste tn: %d  fp: %d fn: %d tp: %d" % (tn, fp, fn, tp))
print(confusion_matrix(y_calc_test,y_obs_test))



if MELHOR_PRECISAO< PrecTeste:
  MELHOR_PRECISAO=PrecTeste
  MAT0=np.copy(syn0)
  MAT1=np.copy(syn1)
  CONF_teste=np.copy(confusion_matrix(y_calc_test,y_obs_test))
  CONF_treino=np.copy(confusion_matrix(y_calc_train,y_obs_train))



Epocas= 300000 Learning rate= 0.0001 Dados teste matriz confusao:
Index(['DI RELATIVO', 'FRAC Its', 'Fo', 'CRo'], dtype='object')
Treino precisao global= 0.9504950495049505
Treino tn: 52  fp: 1 fn: 4 tp: 44
[[52  1]
 [ 4 44]]
Teste: precisao global= 0.64
Teste tn: 6  fp: 5 fn: 4 tp: 10
[[ 6  5]
 [ 4 10]]


In [27]:
print("Melhor precisao=",MELHOR_PRECISAO)
print(MAT0)
print(MAT1)
nl0=MAT0.shape[0];nc0=MAT0.shape[1]
nl1=MAT1.shape[0];nc1=MAT1.shape[1]
print("colunas %d e linhas %d MAT0" % (nc0,nl0))
print("colunas %d e linhas %d MAT1" % (nc1,nl1))
print(CONF_teste)
print(CONF_treino)

Melhor precisao= 0.64
[[ 1.62628641 -3.38729939  0.88844333 -2.82382476 -2.08813839  1.78248921
   1.07886145  0.97158851 -0.65142667]
 [ 1.43932519 -3.51954698 -0.13915334  2.0424967  -0.52942021 -0.79999248
  -1.25305698 -0.50692839  0.13036965]
 [-1.06054899  2.44184096 -3.66742568 -0.10680904 -3.38050656 -7.00591235
   0.16485462  1.20681471  0.98874816]
 [-0.45709058  1.50291822  0.3131551  -5.5622364   0.32914341  0.18298895
  -0.14240124 -0.19474124  3.1463624 ]]
[[ 2.73739523]
 [ 1.53729752]
 [-2.18551569]
 [ 0.86817614]
 [-2.27374849]
 [ 1.95500084]
 [ 2.51002369]
 [-4.80775   ]
 [ 0.88301994]]
colunas 9 e linhas 4 MAT0
colunas 1 e linhas 9 MAT1
[[ 6  5]
 [ 4 10]]
[[52  1]
 [ 4 44]]


In [28]:
Nomes=['OTIMO','PARTIC_best','Xresp']
print("Melhor precisao=",MELHOR_PRECISAO)
#print(MAT0)
#print(MAT1)
nl0=MAT0.shape[0];nc0=MAT0.shape[1]
nl1=MAT1.shape[0];nc1=MAT1.shape[1]
print("colunas %d e linhas %d MAT0" % (nc0,nl0))
print("colunas %d e linhas %d MAT1" % (nc1,nl1))
print(CONF_teste)
print(CONF_treino)
#BUSCA=pd.Series([OTIMO,PARTIC_best,Xresp],index=Nomes )

Melhor precisao= 0.64
colunas 9 e linhas 4 MAT0
colunas 1 e linhas 9 MAT1
[[ 6  5]
 [ 4 10]]
[[52  1]
 [ 4 44]]


In [29]:
dim=np.array([[nl0,nc0],[nl1,nc1]])
Dummies=['hello pandas I am envolving']
Armazenar=['Dummie','MAT0','MAT1','dim','Conf_treino','Conf_teste','precisao']
BUSCA=pd.Series([Dummies,MAT0,MAT1,dim,CONF_treino,CONF_teste,MELHOR_PRECISAO],index=Armazenar )
BUSCA = pd.DataFrame(BUSCA) 
print(BUSCA)


                                                             0
Dummie                           [hello pandas I am envolving]
MAT0         [[1.626286409745978, -3.387299391470142, 0.888...
MAT1         [[2.7373952278090052], [1.5372975193980174], [...
dim                                           [[4, 9], [9, 1]]
Conf_treino                                 [[52, 1], [4, 44]]
Conf_teste                                   [[6, 5], [4, 10]]
precisao                                                  0.64


In [30]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [0]:
from datetime import datetime
nowfname=datetime.now().strftime("%Y-%m-%d_%Hh%Mmin")

In [32]:
BUSCA.to_csv(('ANN_'+ nowfname +'.csv'))
print(('ANN_'+ nowfname +'.csv'))
ARQ='ANN_'+ nowfname +'.csv'

ANN_2019-10-18_20h20min.csv


In [39]:
#!cp 2019-10-05_03h42min_DE_Michalewicz_10.csv drive/My\ Drive/imput_ANN/
!cp  ANN_2019-10-18_20h20min.csv drive/My\ Drive/

cp: cannot stat 'ANN_2019-10-18_20h20min.csv': No such file or directory


In [34]:
!git clone https://github.com/ucfilho/ANN_read_matrix #clonar do Github
%cd ANN_read_matrix

fatal: destination path 'ANN_read_matrix' already exists and is not an empty directory.
/content/ANN/ANN_read_matrix


In [0]:
ANN=pd.read_csv('ANN_2019-10-18_19h35min.csv')

In [36]:
print(type(ANN))

<class 'pandas.core.frame.DataFrame'>


In [37]:
print(ANN)

          MAT0  \
0         MAT1   
1          dim   
2  Conf_treino   
3   Conf_teste   
4     precisao   

  [[-0.74029023  1.5334461   1.06309715  3.24617844 -1.85171561  0.99413037\n  -1.42682206 -3.58046796 -2.89970909]\n [-8.06210354  0.49355243 -0.52641372 -0.85449969  2.44333055 -0.25223886\n   1.86785186 -1.74063979 -2.43694128]\n [ 1.22802109 -5.65634949 -2.0697304   0.67415639 -2.5248747   3.87458595\n  -3.15916184 -3.55246295  0.75940016]\n [-1.0082497  -0.77309616 -4.25116871  3.84303333 -0.68333364 -0.73761302\n   0.36389525  2.37952324  0.43109882]]  
0  [[ 0.85185649]\n [ 1.25215988]\n [-0.65306564]...                                                                                                                                                                                                                                                                                                                                                                                       

In [38]:
A=np.array(ANN.iloc[0][1])
B=np.array(ANN.iloc[1][1])
C=np.array(ANN.iloc[2][1])
print(A)
print(B)
print(C)

[[ 0.85185649]
 [ 1.25215988]
 [-0.65306564]
 [-0.92490046]
 [-1.84796588]
 [ 3.96705636]
 [ 3.36983036]
 [ 1.99028552]
 [-1.14250223]]
[[4 9]
 [9 1]]
[[50  2]
 [ 4 45]]
